import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '@/components/Header';
import { useMDXComponent } from 'next-contentlayer/hooks';
import AboutMe from '@/components/content/AboutMe';
import Footer from '@/components/Footer';
import AuthorLayout from '@/layouts/AuthorLayout';

import siteMetadata from '@/data/siteMetadata';

import { allPages, Page } from '@/lib/contentLayerAdapter';

export function getStaticProps() {
  const page = allPages.find((page) => page.slug === 'about-me');
  return { props: { page } };
}

type Props = {
  page: Page;
};

const Home: NextPage<Props> = ({ page }) => {
  const MDXContent = useMDXComponent(page.body.code);
  return (
    <>
      <Head>
        <title>{siteMetadata.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutMe />
      <AuthorLayout>
        <MDXContent />
      </AuthorLayout>
    </>
  );
};

export default Home;
