import Head from 'next/head';

import ContainerWrapper, { Size } from '@/components/Wrapper/ContainerWrapper';
import ProjectLayout from '@/layouts/ProjectLayout';

import siteMetadata from '@/data/siteMetadata';

const Projects: React.FC = () => {
  return (
    <>
      <Head>
        <title>{siteMetadata.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon/favicon.ico" />
      </Head>
      <ContainerWrapper size={Size.lg}>
        <ProjectLayout />
      </ContainerWrapper>
    </>
  );
};

export default Projects;
